import tempfile
import unittest
from pathlib import Path

from testing_framework.source_provenance import scan_source_provenance


class SourceProvenanceTests(unittest.TestCase):
    def scan(self, root, **options):
        files = [path for path in root.rglob("*") if path.is_file()]
        return scan_source_provenance(root, files, **options)

    def test_detects_explicit_authorship_marker(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            marker = "Generated by " + "Chat" + "GPT"
            (root / "service.py").write_text(f"# {marker}\nprint('ok')\n", encoding="utf-8")
            signals, scanned = self.scan(root)
            self.assertEqual(scanned, 1)
            self.assertEqual(len(signals), 1)
            self.assertEqual(signals[0].line, 1)

    def test_does_not_flag_legitimate_product_integration(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            vendor = "Open" + "AI"
            (root / "client.py").write_text(f"class {vendor}Client:\n    pass\n", encoding="utf-8")
            signals, _ = self.scan(root)
            self.assertEqual(signals, [])

    def test_detects_generic_assistance_statement(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            marker = "Devel" + "oped with the help of " + "AI"
            (root / "service.ts").write_text(f"// {marker}\n", encoding="utf-8")
            signals, _ = self.scan(root)
            self.assertEqual(len(signals), 1)
            self.assertEqual(signals[0].confidence, "medium")

    def test_detects_assistant_configuration_artifact(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            filename = "CLA" + "UDE.md"
            (root / filename).write_text("project rules", encoding="utf-8")
            signals, _ = self.scan(root)
            self.assertEqual(len(signals), 1)
            self.assertEqual(signals[0].kind, "arquivo de configuração de assistente")

    def test_honors_allowlist_and_exclude(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            marker = "Code gen" + "erated by " + "AI"
            (root / "accepted.py").write_text(f"# {marker}", encoding="utf-8")
            generated = root / "generated"
            generated.mkdir()
            (generated / "file.py").write_text(f"# {marker}", encoding="utf-8")
            signals, _ = self.scan(root, allowlist=["accepted.py"], exclude=["generated/*"])
            self.assertEqual(signals, [])


if __name__ == "__main__":
    unittest.main()
